### ISSUE TITLE
reset fails using sqlite3

### ISSUE THREAD

**Issue by ghost** [andrewpillar/mgrt#1]
`mgrt reset` fails using sqlite3.

Git revision `f5f6d68b6f56ec52d6228d18519fc3094f98499e`

### Configuration

```toml
type = "sqlite3"
address = "/tmp/db.sqlite3"
database = ""
username = ""
password = ""
```

### Add Revision

```bash
$ mgrt add -m "Create users table"
added new revision at:
  revisions/1569919896_create_users_table/up.sql
  revisions/1569919896_create_users_table/down.sql
```
`up.sql`:

```sql
create table "users" (name text);
```
`down.sql`:

```sql
drop table "users";
```

### Run

```bash
$ mgrt run 
up - performed revision: 1569919896: Create users table
```

### Log

```bash
$ mgrt log
Revision: 1569919896 - eb793f5f312170edda1967948d4c6df8c8010f75114db5768131aca74707d459
Date:     Tue Oct 01 11:00:36 2019
Message:  Create users table

    create table "users" (name text);
```

```bash
$ sqlite3 /tmp/db.sqlite3 .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE mgrt_revisions (
                        id         INTEGER NOT NULL,
                        message    TEXT NOT NULL,
                        hash       BLOB NOT NULL,
                        direction  INTEGER NOT NULL,
                        up         TEXT NULL,
                        down       TEXT NULL,
                        forced     INTEGER NOT NULL,
                        created_at TIMESTAMP NOT NULL
                );
INSERT INTO mgrt_revisions VALUES(1569919896,'Create users table',X'eb793f5f312170edda1967948d4c6df8c8010f75114db5768131aca74707d459',0,replace('create table "users" (name text);\n','\n',char(10)),replace('drop table "users";\n','\n',char(10)),0,'2019-10-01 11:00:36.920481984+02:00');
CREATE TABLE IF NOT EXISTS "users" (name text);
COMMIT;
```

### Reset

```bash
$ mgrt reset
/home/lutz/go/bin/mgrt: failed to perform revision: no such column: false: 1569919896
```

**Comment by andrewpillar** [comment]
Unable to reproduce this one, could I get the output of `go version`
and `go env`. For comparison here's mine:

$ go version
go version go1.13 linux/amd64
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/andrew/go/bin"
GOCACHE="/home/andrew/.cache/go-build"
GOENV="/home/andrew/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/andrew/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-
map=/tmp/go-build221411976=/tmp/go-build -gno-record-gcc-switches"

**Comment by ghost** [comment]
```
$ go version
go version go1.13 linux/amd64
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lutz/.cache/go-build"
GOENV="/home/lutz/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/lutz/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build621899430=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by andrewpillar** [comment]
Hmm, interesting. What version of SQLite 3? Also, see below the
recording I made where I tried replicating your issue.

https://asciinema.org/a/LJWBfnTC3Ky8fhjqr0MLjxyxx

Judging by the error I'm guessing this is something to do with the
string interpolation of the query that logs each revision that is
performed.

**Comment by ghost** [comment]
SQLite as it comes with Ubuntu 18.04:

```
$ sqlite3 --version
3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt1
```

**Comment by andrewpillar** [comment]
Built on Ubuntu 18.04 and re-ran using the same SQLite 3 version, still not
able to replicate the error, how did you build mgrt, using the Makefile or the
`go` commands?

See below the recording I took of running the commands on Ubuntu 18.04

https://asciinema.org/a/tqd6KZTYYsniaFbvM5FDIvcYj
