### ISSUE TITLE
No more down revisions?

### ISSUE THREAD

**Issue by chainlink** [andrewpillar/mgrt#4]
Hi there,
Thanks for writing this library, it's been really useful for our app! I'm curious of your thoughts on getting rid of down migrations in the latest iteration of the library. Is the plan to add these later? Is the idea just to make another revision if you need to revert/do a down migration? Cheers!

**Comment by andrewpillar** [comment]
The idea is to write a revision that does the inverse of what you want. This is an intentional design decision, it makes the implementation simpler when you only have to work with a list of revisions that are applied to a database one after the other.

**Comment by chainlink** [comment]
Makes sense! I actually quite like it as well, as implementing revert / down is tricky in a git driven CI/CD environment.
